name = "wasm-example-router"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release"